DROP TABLE STUDENT_T;
CREATE TABLE STUDNET_T (
        STUDENT_NO  NUMBER NOT NULL
      , NAME        VARCHAR2(100 BYTE) NOT NULL
      , KOREAN      NUMBER
      , ENGLISH     NUMBER
      , MATH        NUMBER
      , AVERAGE     NUMBER
      , CONSTRAINT PK_STU PRIMARY KEY(STU_NO)
);

DROP SEQUENCE STUDENT_SEQ;
CREATE SEQUENCE STUDENT_SEQ NOCACHE;